#ifndef __NG_CONFIG_H_
#define __NG_CONFIG_H_

#define SCREEN_WIDTH 320
#define SCREEN_HEIGHT 240

#define CPU6502_MEMORY_SIZE  0x10000 // 64k
#define GFX_MEMORY_SIZE 320*240

#define MEMORY_MAP_START 0x2000
#define MEMORY_MAP_END   0x20ff 

#define MEMORY_TILES_WIDTH  40
#define MEMORY_TILES_HEIGHT 30
#define MEMORY_TILES_TOTALSPACE (MEMORY_TILES_WIDTH*MEMORY_TILES_HEIGHT)
#define MEMORY_TILEAREA_START (MEMORY_MAP_END+1)
#define MEMORY_TILEAREA_END (MEMORY_TILEAREA_START+MEMORY_TILES_TOTALSPACE)

#endif