#ifndef __NG_CONFIG_H_
#define __NG_CONFIG_H_

#include "../ng_defines.h"
#include "ng_api_shared.h"

#define SCREEN_WIDTH 320
#define SCREEN_HEIGHT 240

#define CPU6502_MEMORY_SIZE  0x10000 // 64k
#define GFX_MEMORY_SIZE 320*240

#define GFX_RENDERQUEUE_MAX_ELEMENTS 5


// sizes should be uneven so that the next address will start on an even number
// otherwise ARM might not like that and crash. ARM don't like to use unaligned addresses ;)
#define MEMORY_MAP_VARS_START 0xe000
#define MEMORY_MAP_VARS_END   (MEMORY_MAP_VARS_START+39)

#define MEMORY_MAP_FUNC_START (MEMORY_MAP_VARS_END+1)
#define MEMORY_MAP_FUNC_END   (MEMORY_MAP_FUNC_START+0x4f)

#define MEMORY_MAP_CALL_BUFFER_BEGIN (MEMORY_MAP_FUNC_END + 1)
#define MEMORY_MAP_CALL_BUFFER_END   (MEMORY_MAP_CALL_BUFFER_BEGIN + 31)

#define MEMORY_MAP_CALLRETURN_BUFFER_BEGIN (MEMORY_MAP_CALL_BUFFER_END+1)
#define MEMORY_MAP_CALLRETURN_BUFFER_END (MEMORY_MAP_CALLRETURN_BUFFER_BEGIN+13)

#define MEMORY_TILES_WIDTH  40
#define MEMORY_TILES_HEIGHT 30
#define MEMORY_TILES_TOTALSPACE (MEMORY_TILES_WIDTH*MEMORY_TILES_HEIGHT)

#define FUNCTION_RETURN_OK 0x01
#define FUNCTION_RETURN_ERROR 0x02

#define MEMORY_TILEAREA_BEGIN (MEMORY_MAP_CALLRETURN_BUFFER_END+1)
#define MEMORY_TILEAREA_END (MEMORY_TILEAREA_BEGIN+MEMORY_TILES_TOTALSPACE)

#endif