;
; File generated by cc65 v 2.18 - Ubuntu 2.19-1
;
	.fopt		compiler,"cc65 v 2.18 - Ubuntu 2.19-1"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.export		_main

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

	ldx     #$04
	lda     #$B0
	jsr     pushax
	jsr     decsp2
	lda     #$00
	jsr     pusha
	lda     #$03
	jsr     pusha
	ldy     #$02
	lda     #$00
	sta     (sp),y
	lda     #$21
	iny
	sta     (sp),y
L0009:	ldy     #$03
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	sta     regsave
	stx     regsave+1
	clc
	adc     #$01
	bcc     L000F
	inx
L000F:	jsr     staxysp
	lda     regsave
	ldx     regsave+1
	jsr     pushax
	ldy     #$03
	lda     (sp),y
	pha
	clc
	adc     #$01
	sta     (sp),y
	pla
	ldy     #$00
	jsr     staspidx
	ldy     #$05
	lda     (sp),y
	tax
	dey
	lda     (sp),y
	sec
	sbc     #$01
	bcs     L0012
	dex
L0012:	jsr     staxysp
	ldy     #$04
	lda     (sp),y
	iny
	ora     (sp),y
	bne     L0009
	ldy     #$02
	sta     (sp),y
	lda     #$21
	iny
	sta     (sp),y
	iny
	lda     #$B0
	sta     (sp),y
	tya
	iny
	sta     (sp),y
	ldy     #$00
	lda     (sp),y
	pha
	sec
	sbc     #$01
	sta     (sp),y
	pla
	bne     L0009
	jsr     push0
	ldy     #$04
	lda     #$5A
	sta     (sp),y
	lda     #$21
	iny
	sta     (sp),y
	jmp     L0028
L0035:	lda     (sp),y
	tax
	dey
	lda     (sp),y
	sec
	sbc     #$01
	bcs     L002C
	dex
L002C:	jsr     stax0sp
L0028:	ldy     #$00
	lda     (sp),y
	iny
	ora     (sp),y
	bne     L0035
	dey
	lda     #$FF
	sta     (sp),y
	tya
	iny
	sta     (sp),y
	ldy     #$07
	jsr     pushwysp
	ldy     #$05
	lda     (sp),y
	pha
	clc
	adc     #$01
	sta     (sp),y
	pla
	ldy     #$00
	jsr     staspidx
	jmp     L0028

.endproc

