/* Autogenerated by hxtools bin2c */
#ifndef GEN_PRG1_H
#define GEN_PRG1_H 1

#ifdef __cplusplus
extern "C" {
#endif

extern const unsigned char bin2c_prg1_bin[893];

#ifdef __cplusplus
} /* extern "C" */
#endif


#endif /* GEN_PRG1_H */
